Update intial index page with admin panel design
DimitarSamarov07/esp-cloud-remote pull request #1
Opened 2024-10-30 15:49 UTC by DelHamzo

2024-11-03 19:48 UTC, DimitarSamarov07 requested changes
Let me know if you have any questions.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +    <div class="footer">
The .footer and .copyright should be a under a footer tag. Read about semantic HTML.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +    <nav class="navbar">
Have a clear separation of semantic HTML tags. First, you have the header, then the body and finally the footer. Add the semantic tags and separate accordingly.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/public/styles.css
> +.footer {
The footer should have a fixed position - it should always be at the bottom of the page. The way you've coded it, it's dependant on the body size. Fix that. Either extend the body to the height of the page so the footer stays at the bottom or somehow use absolute positioning. The footer has to not look out of place. If you are not able to replicate the issue on your end, zoom out the web page.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +    <div class="copyright">
Should be a part of the footer.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/public/styles.css
> +    text-decoration: none;
You use this quite a lot. Why don't you make it a global rule for the anchor tags?

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/public/styles.css
> +    padding: 0.5% 5% 0.5% 5%;
Using percentages for padding in this case isn't the best idea as it's not clear what this means(a percentage of what and why?). Either use pixels or something else.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/public/styles.css
> +    list-style: none;
You use list-style quite a few times. Make it a global rule for ul, so you don't have to repeat it.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +                        <span>ESP-8266</span>
Kindly avoid using spans. Please replace them with something else.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +        <span>ESP Cloud Remote @ 2024</span>
Change the span, please.

2024-11-03 19:48 UTC, DimitarSamarov07 commented on Front-End/index.html
> +                    <td style="color: #00c774;">Active</td>
Never use inline style tags! Keep the CSS in the CSS file.

2024-11-05 10:58 UTC, DelHamzo reviewed
fixed

2024-11-05 17:50 UTC, DimitarSamarov07 approved these changes
Looks good!

2024-11-05 17:52 UTC, merged